### ISSUE TITLE
Sometimes the search results are empty, how should I troubleshoot the issue?

### ISSUE THREAD

**Issue by photkey** [opsdisk/yagooglesearch#36]
I used a proxy IP for the search, and sometimes when using the exact same keywords, the search results are empty, while other times there are results. I suspect it is due to the quality of the proxy IP, but I am not sure how to confirm the cause of the problem or how to resolve it.
Can this library add a return similar to `HTTP_429_DETECTED`, which is a prompt returned in case of network issues, for example: `HTTP_ERROR`? This can be used in the script to handle this result, such as changing the proxy

**Comment by opsdisk** [comment]
Hi @photkey apologies it took a while to get back to you.  Two quick things...

* As a reminder, check out https://github.com/opsdisk/yagooglesearch#multiple-proxies
* If you're using free proxies, you kind of get what you pay for...build out your own proxy infrastructure or use paid / higher quality ones

Do you get back a specific HTTP error code (401, 404, etc.) when results are empty?  The HTTP 429 is easy because that relates to interacting with Google itself.  If empty results are returned, that may be because there are literally no results...and how is yagooglesearch supposed to know the difference between empty results and your hypothesis that it is networked related?

Your current solution to have your script handle the empty results is correct in my opinion.  Your script understands the context of the network, proxies, timing, etc. much better than yagooglesearch does.  Again, check out https://github.com/opsdisk/yagooglesearch#multiple-proxies

If I'm not understanding your question or situation correctly, let me know.

**Comment by opsdisk** [comment]
Any updates on this @photkey ?

**Comment by opsdisk** [comment]
Great to hear, I'll close this issue out then.
